[env:azoth_esp32_s3_n16r8]
platform = espressif32
board = azoth_esp32_s3_n16r8
framework = arduino
monitor_speed = 115200
upload_speed = 460800

build_flags =
    -mfix-esp32-psram-cache-issue

; --- Port Linux actuel: driver cdc_acm pour la puce CH343 ---
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
upload_flags =
    --before=no_reset
    --after=hard_reset
lib_deps =
    lovyan03/LovyanGFX @ ^1.1.12
